# Site settings
title: Vulcain Trading
description: Votre présence en Chine — représentation, sourcing et conseil
email: ivy.chang@vulcain-trading.com

# Build settings
theme: jekyll-theme-minimal
# google_analytics: UA-54334713-2

# defaults:
#  - scope:
#      path: "assets/img"
#    values:
#      image: true
