# Site settings
title: Vulcain Trading
description:
  fr: Votre présence en Chine — représentation, sourcing et conseil
  en: Your presence in China - representation, sourcing and consulting
email: ivy.chang@vulcain-trading.com
index:
  en: index.html
  fr: index_fr.html

# Build settings
theme: jekyll-theme-minimal
google_analytics: UA-54334713-2

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
