
# Site settings
title: Vulcain Trading
description: Votre présence en Chine — représentation, sourcing et conseil
email: contact@vulcain-trading.com
wechat: Chang_xiangxiang

# Build settings
theme: jekyll-theme-minimal

google_analytics: UA-54334713-2

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
